### PR TITLE
Update fork and bump editor version

### PR DESCRIPTION
**Pull request by magistrula**
### Purpose
- Pull in latest updates to `ember-cli-medium-editor` from [trunk](https://github.com/lukebrenton/ember-cli-medium-editor) and update the version of `medium-editor` to `5.23.3`.

### CODE REVIEW

**Review by thomaswrenn — APPROVED** [review]
@magistrula any reason why they haven't upgraded to medium-editor 5.23.3? Maybe good to give them a pull request as a followup? Doesn't look like there's test in this repo to verify but this addon looks like a thin enough layer that it should be readily apparent if anything breaks 👍 

LGTM

**Comment by magistrula** [comment]
@thomaswrenn The last update to `ember-cli-medium-editor` was a year ago, so I guess they haven't upgraded because the maintainers are no longer actively maintaining the project.

**Comment by magistrula** [comment]
I pinged the owner of `ember-cli-medium-editor` on Slack; we'll see what he says.

**Comment by magistrula** [comment]
This update caused failing tests in vishnu-frontend due to browser disconnected errors. Closing this for now, as we don't currently have time to invest in figuring out the source of the problem.

**Comment by nnegri** [comment]
Reopening to see if we can get this to pass in Circle, and address this bug: https://altschool.atlassian.net/browse/ALTOS-16539

**Comment by magistrula** [comment]
@nnegri Should we keep this PR open?

**Comment by nnegri** [comment]
@magistrula I'll close it again for now, might reopen to try again next time I'm on prod alerts.

**Pull request closed without merging**
